version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    post_install:
      - bash examples/run_examples.sh

python:
  install:
    - requirements: requirements/requirements.txt
    - requirements: requirements/requirements_docs.txt
    - method: setuptools
      path: .
  system_packages: true

sphinx:
  configuration: docs/conf.py
