version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - bash examples/run_examples.sh

python:
  install:
    - requirements: requirements/requirements.txt
    - method: pip
      path: .[docs]

sphinx:
  configuration: docs/conf.py
