version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - git clone https://github.com/equinor/fmu-datamodels ../fmu-datamodels
    post_install:
      - pip install ../fmu-datamodels
      - bash examples/update_examples.sh

python:
  install:
    - method: pip
      path: .[docs]

sphinx:
  configuration: docs/src/conf.py
