"""Test the tsurf readers module"""

from pathlib import Path

import numpy as np

from fmu.dataio._readers import tsurf_file_reader as reader


def _create_hardcoded_file(filepath: Path):
    """Create a hardcoded TSurf file for testing purposes."""

    with open(filepath, "w") as file:
        file.write("""GOCAD TSurf 1
HEADER {
name: Fault F1
}
GOCAD_ORIGINAL_COORDINATE_SYSTEM
NAME Default
AXIS_NAME "X" "Y" "Z"
AXIS_UNIT "m" "m" "m"
ZPOSITIVE Depth
END_ORIGINAL_COORDINATE_SYSTEM
TFACE
VRTX 1 0.1 0.2 0.3 CNXYZ
VRTX 2 1.1 1.2 1.3 CNXYZ
VRTX 3 2.1 2.2 2.3 CNXYZ
VRTX 4 3.1 3.2 3.3 CNXYZ
TRGL 1 2 3
TRGL 1 2 4
END
""")


def _create_dummy_TSurfFileData():
    """Create a dummy TSurfFileData object for testing purposes."""

    tsurf_dict = {}
    tsurf_dict["header"] = {"name": "Fault F1"}
    tsurf_dict["coordinate_system"] = {
        "name": "Default",
        "axis_name": ("X", "Y", "Z"),
        "axis_unit": ("m", "m", "m"),
        "zpositive": "Depth",
    }
    tsurf_dict["vertices"] = np.array(
        [
            (0.1, 0.2, 0.3),
            (1.1, 1.2, 1.3),
            (2.1, 2.2, 2.3),
            (3.1, 3.2, 3.3),
        ]
    ).astype(np.float64)
    tsurf_dict["triangles"] = np.array([(1, 2, 3), (1, 2, 4)]).astype(np.int64)

    return reader.create_TSurfFileData(tsurf_dict)


def test_create_TSurfFileData():
    """Test the creation of a TSurfFileData object from a dictionary."""

    instance = _create_dummy_TSurfFileData()

    # Test the data
    assert isinstance(instance, reader.TSurfFileData)
    assert instance.header.name == "Fault F1"
    assert instance.coordinate_system.name == "Default"
    assert instance.coordinate_system.axis_name == ("X", "Y", "Z")
    assert instance.coordinate_system.axis_unit == ("m", "m", "m")
    assert instance.coordinate_system.zpositive == "Depth"
    assert len(instance.vertices) == 4
    assert isinstance(instance.vertices, np.ndarray)
    assert instance.vertices.dtype == np.float64
    assert isinstance(instance.vertices[0], np.ndarray)
    assert instance.vertices[0].dtype == np.float64
    assert (instance.vertices[0] == np.array([0.1, 0.2, 0.3])).all()
    assert (instance.vertices[-1] == np.array([3.1, 3.2, 3.3])).all()
    assert len(instance.triangles) == 2
    assert isinstance(instance.triangles, np.ndarray)
    assert instance.triangles.dtype == np.int64
    assert isinstance(instance.triangles[0], np.ndarray)
    assert instance.triangles[0].dtype == np.int64
    assert (instance.triangles[0] == np.array([1, 2, 3])).all()
    assert (instance.triangles[-1] == np.array([1, 2, 4])).all()


def test_tsurf_reader_writer_hardcoded_file(rootpath):
    """Test the in-house TSurf reader/writer."""

    # Create dummy TSurf test file
    # TODO: OK to save it here?
    relpath = "tests/data/drogon/rms/output/structural/hardcoded.ts"
    filepath = rootpath / relpath
    _create_hardcoded_file(filepath)
    assert filepath.exists()

    try:
        # Read the file
        instance = reader.read_tsurf_file(filepath)

        # Test the data
        assert isinstance(instance, reader.TSurfFileData)
        assert instance.header.name == "Fault F1"
        assert instance.coordinate_system.name == "Default"
        assert instance.coordinate_system.axis_name == ("X", "Y", "Z")
        assert instance.coordinate_system.axis_unit == ("m", "m", "m")
        assert instance.coordinate_system.zpositive == "Depth"
        assert len(instance.vertices) == 4
        assert isinstance(instance.vertices, np.ndarray)
        assert instance.vertices.dtype == np.float64
        assert isinstance(instance.vertices[0], np.ndarray)
        assert instance.vertices[0].dtype == np.float64
        assert (instance.vertices[0] == np.array([0.1, 0.2, 0.3])).all()
        assert (instance.vertices[-1] == np.array([3.1, 3.2, 3.3])).all()
        assert len(instance.triangles) == 2
        assert isinstance(instance.triangles, np.ndarray)
        assert instance.triangles.dtype == np.int64
        assert isinstance(instance.triangles[0], np.ndarray)
        assert instance.triangles[0].dtype == np.int64
        assert (instance.triangles[0] == np.array([1, 2, 3])).all()
        assert (instance.triangles[-1] == np.array([1, 2, 4])).all()

    finally:
        # Remove the file
        filepath.unlink()
        assert not filepath.exists()


def test_tsurf_reader_RMS_file(rootpath):
    """Test the in-house TSurf reader/writer."""

    # The TSurf file 'F5.ts' was generated by RMS
    relpath = "tests/data/drogon/rms/output/structural/F5.ts"
    filepath = rootpath / relpath

    instance = reader.read_tsurf_file(filepath)

    assert instance.header.name == "F5"
    assert instance.coordinate_system.name == "Default"
    assert instance.coordinate_system.axis_name == ("X", "Y", "Z")
    assert instance.coordinate_system.axis_unit == ("m", "m", "m")
    assert instance.coordinate_system.zpositive == "Depth"
    assert len(instance.vertices) == 44
    assert (
        instance.vertices[0] == np.array([459621.051270, 5934843.011475, 1685.590820])
    ).all()
    assert (
        instance.vertices[-1] == np.array([459651.376465, 5936259.713867, 1721.204224])
    ).all()
    assert len(instance.triangles) == 65
    assert (instance.triangles[0] == np.array([24, 25, 28])).all()
    assert (instance.triangles[-1] == np.array([43, 8, 44])).all()


def test_tsurf_writer(rootpath):
    """Test the in-house TSurf writer."""

    instance = _create_dummy_TSurfFileData()
    relpath = "tests/data/drogon/rms/output/structural/dummy.ts"
    filepath = rootpath / relpath

    try:
        reader.write_tsurf_file(instance, filepath)
        read_instance = reader.read_tsurf_file(filepath)

        # assert instance == read_instance
        # TODO: ensure that content is checked, not only references
        # TODO: need to implement __eq__ method in TSurfFileData, see
        # https://stackoverflow.com/questions/51743827/how-to-compare-equality-of-dataclasses-holding-numpy-ndarray-boola-b-raises

    finally:
        # Remove the file
        filepath.unlink()
        assert not filepath.exists()


def test_tsurf_data_validation():
    """Test the TSurf data validation of each field."""

    # TODO: validate the data of each field in the TSurfFileData: key and value
    # TODO: both on object instantiation and when changing a field
    # in an existing object

    tsurf_dict = {}
    tsurf_dict["header"] = {"name": "Fault F1"}
    tsurf_dict["coordinate_system"] = {
        "name": "Default",
        "axis_name": ("X", "Y", "Z"),
        "axis_unit": ("m", "m", "m"),
        "zpositive": "Depth",
    }
    tsurf_dict["vertices"] = np.array(
        [
            (0.1, 0.2, 0.3),
            (1.1, 1.2, 1.3),
            (2.1, 2.2, 2.3),
            (3.1, 3.2, 3.3),
        ]
    ).astype(np.float64)
    tsurf_dict["triangles"] = np.array([(1, 2, 3), (1, 2, 4)]).astype(np.int64)

    assert reader.create_TSurfFileData(tsurf_dict)
    # TODO: check some of the fields

    # Invalid field in header
    tsurf_dict_faultname = tsurf_dict.copy()
    tsurf_dict_faultname["header"] = {"invalid": "Fault F1"}

    # TODO: doesn't work yet, doesn't raise KeyError
    # with pytest.raises(KeyError):
    #     reader.create_TSurfFileData(tsurf_dict)

    # General pattern:
    # with pytest.raises(ValueError, match="Can't use absolute path as 'forcefolder'"):


    # TODO: continue with more tests
