import json

from fmu.dataio._model import dump


def test_schema_uptodate():
    # ruff: noqa: E501
    """
    Test to verify if the local schema is up to date with the schema
    generated by pydantic's `dump` method. It compares the content of
    the local `fmu_results.json` with the output of `dump()`.

    To update the local schema, run:
    `./tools/update_schema`
    """
    with open("schemas/0.8.0/fmu_results.json") as f:
        assert json.load(f) == dump()


def contains_discriminator_mapping(schema):
    """Recursively checks ["discriminator"]["mapping"] in the schema."""
    if isinstance(schema, dict):
        if (
            "discriminator" in schema and isinstance(schema["discriminator"], dict)
        ) and "mapping" in schema["discriminator"]:
            return True
        for value in schema.values():
            if contains_discriminator_mapping(value):
                return True
    elif isinstance(schema, list):
        for item in schema:
            if contains_discriminator_mapping(item):
                return True
    return False


def test_no_discriminator_mappings_leftover_in_schema():
    """Sumo's AJV validator doesn't like discriminator mappings leftover in the
    schema."""
    with open("schemas/0.8.0/fmu_results.json") as f:
        schema = json.load(f)
    assert contains_discriminator_mapping(schema) is False
