#!/usr/bin/env python

import sys
from pathlib import Path

import xtgeo

import fmu.dataio as dataio
from fmu.config import utilities as ut


def main() -> None:
    project_path = Path(sys.argv[1])
    CFG = ut.yaml_load(project_path / "fmuconfig/output/global_variables.yml")
    surf = xtgeo.surface_from_file(
        project_path / "ert/output/maps/props/poro_average.gri"
    )
    dataio.ExportData(
        config=CFG,
        name="all",
        unit="fraction",
        vertical_domain="depth",
        domain_reference="msl",
        content="property",
        timedata=None,
        is_prediction=True,
        is_observation=False,
        tagname="average_poro",
        workflow="rms property model",
    ).export(surf)


if __name__ == "__main__":
    main()
