# build and test some end points
name: Build and deploy docs for fmu-dataio

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build_pywheels:
    name: PY ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and build docs
        run: |
          pip install pip -U && pip install wheel -U
          pip install .[docs]
          pip install xtgeo==2.15rc3
          pip install git+https://github.com/equinor/fmu-config
          sh examples/run_examples.sh
          python setup.py build_sphinx
      - name: Commit documentation changes
        run: |
          mkdir -p gh-pages
          cp -R build/sphinx/html/* gh-pages/
          # cd gh-pages
          # git add .
          # git commit -m "Update documentation" -a || true
          # # The above command fails if no changes, so we ignore the return code.
      - name: Push changes
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh_pages
          publish_branch: gh-pages-pr
          allow_empty_commit: true
          # user_name: "github-actions[bot]"
          # user_email: "github-actions[bot]@users.noreply.github.com"
