name: Test building docs for fmu-dataio

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install fmu-dataio
        run: |
          pip install -U pip
          pip install .[docs]
      
      # Install repos from their Github main branches instead of Pypi.
      # This removes the need to manually pin these version of the repos
      # during the development phase.

      - name: Install fmu-datamodels
        run: |
          pip install \
            "fmu-datamodels @ git+https://github.com/equinor/fmu-datamodels.git"

      - name: Generate updated examples
        run: sh examples/update_examples.sh

      - name: Build documentation with sphinx
        run: sphinx-build -b html docs/src build/docs/html -j auto
